;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
gpush=git push  
gpull=git pull $* 
gpushf=git push -f $*  
gstasht=git stash $* 
gr=git reset $* 
gm=git merge $* 
glast=git log -1 HEAD $* 
gus=git reset HEAD -- $* 
gcl=git clone $*  
gs=git status  
ga=git add $*  
gap=git add -p $*  
gc=git commit $*  
gcm=git commit -m $*  
gco=git checkout $*  
gcob=git checkout -b $*  
gd=git diff $*  
gf=git fetch $*  
